apiVersion: v1
kind: Service
metadata:
  name: sb-demo-svc
spec:
  selector:
    app: sb-demo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer


