apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: sb-demo-front
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service sb-demo-svc"]'
spec:
  replicas: 2
  minReadySeconds: 2
  selector:
    matchLabels:
      app: sb-demo
  template:
    metadata:
      labels:
        frontedBy: sb-demo-svc`
    spec:
      containers:
      - name: sb-demo-con
        image: docker.iflat.nhn.com/sb_demo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
