apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service rollout-svc"]'
  labels:
    app: myapp2
  name: myapp2-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - image: docker.iflat.nhn.com/sb_demo
          name: frontend
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
